export const majorChords = [
  {
    key: 1,
    keyCode: 65,
    note: "Db",
    src: "https://omnichord-audio.s3-eu-west-1.amazonaws.com/db-major.wav",
  },
  {
    key: 2,
    keyCode: 83,
    src: "https://omnichord-audio.s3-eu-west-1.amazonaws.com/ab-major.wav",
    note: "Ab",
  },
  {
    key: 3,
    keyCode: 68,
    src: "https://omnichord-audio.s3-eu-west-1.amazonaws.com/eb-major.wav",
    note: "Eb",
  },
  {
    key: 4,
    keyCode: 70,
    src: "https://omnichord-audio.s3-eu-west-1.amazonaws.com/bb-major.wav",
    note: "Bb",
  },
  // {
  //   key: 5,
  //   keyCode: 71,
  //   note: "F",
  //   sample: "",
  //   freq: 698.46,
  // },
  // {
  //   key: 6,
  //   keyCode: 72,
  //   note: "C",
  //   sample: "",
  //   freq: 523.25,
  // },
  // {
  //   key: 7,
  //   keyCode: 74,
  //   note: "G",
  //   sample: "",
  //   freq: 1046.5,
  // },
  // {
  //   key: 8,
  //   keyCode: 75,
  //   note: "D",
  //   sample: "",
  //   freq: 1046.5,
  // },
  // {
  //   key: 9,
  //   keyCode: 76,
  //   note: "A",
  //   sample: "",
  //   freq: 1046.5,
  // },
  // {
  //   key: 10,
  //   keyCode: 59,
  //   note: "E",
  //   sample: "",
  //   freq: 1046.5,
  // },
  // {
  //   key: 11,
  //   keyCode: 222,
  //   note: "B",
  //   sample: "",
  //   freq: 1046.5,
  // },
  // {
  //   key: 12,
  //   keyCode: 220,
  //   note: "F#",
  //   sample: "",
  //   freq: 1046.5,
  // },
]
